### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JLEGit** [dabde/acc_shared_mem_access_python#1]
Hello, 
Your app is just fine, it only displays one driver and not all the drivers present on the server.

**Comment by dabde** [comment]
Hi,

I can only expose given shared memory information from acc. For what is possible to access, I can only refere to the acc documentation: https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

The only value for multiple Cars are the gps coorinates:
https://github.com/dabde/acc_shared_mem_access_python/blob/main/acc_shm_reader.py#L82

**Comment by dabde** [comment]
Closing. Nothing to do.
